#' Repository
#' @name repository-param
#' @param repository A file path to a CRAN repository.
NULL

#' Available Packages
#' @name available_packages-param
#' @param available_packages An object like the one generated by
#' \code{available.packages()}
NULL

#' Compile Packages
#' @name compile-param
#' @param compile boolean - whether or not to compile binary packages. Default
#' TRUE
NULL

#' Quiet Output
#' @name quiet-param
#' @param quiet boolean, TRUE silences output.
NULL

#' Compile Packages and Add to CRAN Repository
#'
#' For a vector of package names and package directories, a path to a directory
#' containing a CRAN repository
#'
#' @param packages A character vector of package names or package directories
#' @inheritParams repository-param
#' @inheritParams available_packages-param
#' @inheritParams compile-param
#' @inheritParams quiet-param
#'
#' @export
add_packages <- function(packages, repository,
                         available_packages = available.packages(),
                         compile = TRUE, quiet = TRUE) {
  zips <- grepl("[.]zip$", packages)
  tars <- grepl("[.](tar[.]gz|tgz)$", packages)
  package_names <- packages[!(zips | tars)]
  zip_packages <- packages[zips]
  tar_packages <- packages[tars]

  package_dir <- file.path(tempdir(), "gitCRAN-package-staging")
  on.exit(unlink(package_dir, TRUE, TRUE))

  sapply(zip_packages, function(url) {
    tf <- tempfile()

    suppressWarnings(
      withCallingHandlers(
        download.file(url, tf),
        warning = function(w) stop(w)
      )
    )

    unzip(tf, exdir = package_dir)
  })

  sapply(tar_packages, function(url) {
    tf <- tempfile()
    suppressWarnings(
      withCallingHandlers(
        download.file(url, tf),
        warning = function(w) stop(w)
      )
    )

    untar(tf, exdir = package_dir)
  })

  packages <- c(package_names, dir(package_dir, full.names = TRUE))

  package_names <- packages[
    is_package_name(packages, clean_available_packages(available_packages))
  ]

  package_dirs <- packages[is_package_dir(packages)]

  if (!setequal(packages, c(package_names, package_dirs)))
    stop(
      "Invalid packages: ",
      setdiff(packages, c(package_names, package_dirs))
    )

  if (length(package_names) > 0)
    add_packages_by_name(package_names, repository, available_packages,
                         compile, quiet)

  if (length(package_dirs) > 0)
    add_package_dirs(package_dirs, repository, available_packages, compile,
                     quiet)

  invisible()
}

is_package_name <- function(package, clean_avail_pkgs) {
  package %in% clean_avail_pkgs$Package
}

is_package_dir <- function(package) {
  dir.exists(package)
}

add_packages_by_name <- function(packages, repository,
                                 available_packages = available.packages(),
                                 compile = TRUE, quiet = TRUE) {
  repository <- normalizePath(repository)

  if (!is_CRAN_repo_dir(repository))
    stop(repository, " does not have CRAN repository structure. ",
         "Be sure it has a src/contrib/PACKAGES file (even if blank) and a ",
         "src/contrib directory. You can also create a repository with these",
         "requirements with CRANpiled::create_repository.")

  download_dir <- get_tempdir("CRANpiled-downloaded-packages")
  on.exit(unlink(download_dir, recursive = TRUE))

  filtered_packages <- filter_existing(packages, repository,
                                       available_packages)

  if (length(filtered_packages) == 0) {
    message("Requested packages (package and version) already in repository.")
    return()
  }

  downloaded_packages <- download.packages(
    pkgs = filtered_packages,
    destdir = download_dir,
    available = available_packages,
    repos = NULL,
    contriburl = character(0),
    quiet = TRUE
  )

  untar_dir <- get_tempdir("CRANpiled-untarred-packages")
  on.exit(unlink(untar_dir, recursive = TRUE))

  untar_results <- sapply(downloaded_packages[, 2], function(tarball) {
    untar(tarball, exdir = untar_dir)
  })

  stopifnot(all(untar_results == 0))

  add_package_dirs(dir(untar_dir, full.names = TRUE), repository,
                   available_packages, compile, quiet)
}

add_package_dirs <- function(package_dirs, repository,
                             available_packages = available.packages(),
                             compile = TRUE, quiet = TRUE) {
  on.exit(unlink(package_dirs, recursive = TRUE))

  repository <- normalizePath(repository)

  stopifnot(is_CRAN_repo_dir(repository))

  dependencies <- get_package_deps(package_dirs, available_packages)

  new_dependencies <- filter_existing(dependencies, repository,
                                      available_packages)
  existing_dependencies <- setdiff(dependencies, new_dependencies)

  if (
    length(filter_installed(existing_dependencies, available_packages)) > 0
  ) {
    withCallingHandlers(
      install.packages(
        filter_installed(existing_dependencies, available_packages),
        repos = paste0("file://", normalizePath(repository)),
        verbose = FALSE,
        quiet = quiet,
        type = "source"
      ),
      warning = stop
    )
  }

  if (length(filter_installed(new_dependencies, available_packages)) > 0) {
    contrib_urls <- unique(available_packages[, "Repository"])
    withCallingHandlers(
      install.packages(
        filter_installed(new_dependencies, available_packages),
        available = available_packages,
        repos = NULL,
        contriburl = contrib_urls,
        verbose = FALSE,
        quiet = quiet,
        type = "source"
      ),
      warning = stop
    )
  }

  withCallingHandlers(
    lapply(package_dirs, install.packages, repos = NULL, type = "source",
           verbose = FALSE, quiet = quiet),
    warning = function(w) stop(w)
  )

  download_dir <- get_tempdir("CRANpiled-downloaded-dependencies")
  on.exit(unlink(download_dir, recursive = TRUE))

  downloaded_packages <- download.packages(
    pkgs = new_dependencies,
    destdir = download_dir,
    available = available_packages,
    repos = NULL,
    contriburl = character(0),
    quiet = TRUE
  )

  package_names <- get_DESCRIPTION_package_name(package_dirs)

  built_packages <- build_package(package_dirs, package_names, compile, quiet)

  built_dependencies <- build_package(
    downloaded_packages[, 2], downloaded_packages[, 1], compile, quiet
  )

  move_to_repo(c(built_packages, built_dependencies), repository)

  tools::write_PACKAGES(file.path(repository, "src", "contrib"))

  cat("Added the following packages to", paste0(repository, ":"),
      paste0(package_names, collapse = ", "), "\n")
  cat("Along with the dependencies to the above packages:",
      paste0(new_dependencies, collapse = ", "), "\n")

  invisible(c(package_names, new_dependencies))
}
